#!/usr/bin/env node
// ── First-time setup script ───────────────────────────────────
const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function main() {
  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║   OpenXchange Portfolio Tracker — Setup          ║');
  console.log('╚══════════════════════════════════════════════════╝\n');

  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('.env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('Generating encryption secret…');
  const secret = crypto.randomBytes(32).toString('hex');

  const port         = await ask('Server port [3001]: ') || '3001';
  const origins      = await ask('Allowed frontend origins [http://localhost:3000]: ') || 'http://localhost:3000';
  const moralisKey   = await ask('Moralis API key (get free at moralis.io): ');

  const envContent = `# Generated by setup.js on ${new Date().toISOString()}
PORT=${port}
NODE_ENV=development

# KEEP THIS SECRET — changing it invalidates all stored API keys
ENCRYPTION_SECRET=${secret}

ALLOWED_ORIGINS=${origins}

DB_PATH=data/tracker.db

MORALIS_API_KEY=${moralisKey || 'your_moralis_key_here'}
ANKR_API_KEY=

LOG_LEVEL=info
`;

  fs.writeFileSync(envPath, envContent);
  fs.mkdirSync(path.join(__dirname, '..', 'data'),   { recursive: true });
  fs.mkdirSync(path.join(__dirname, '..', 'logs'),   { recursive: true });
  fs.mkdirSync(path.join(__dirname, '..', 'public'), { recursive: true });

  console.log('\n✅ Setup complete!\n');
  console.log('Next steps:');
  console.log('  1. Copy your tracker.html into the /public folder');
  console.log('  2. Run: npm install');
  console.log('  3. Run: npm start');
  console.log(`  4. Open: http://localhost:${port}\n`);
  console.log('⚠️  Keep your .env file private — it contains your encryption secret.\n');

  rl.close();
}

main().catch(err => { console.error(err); process.exit(1); });
